---

   - name : Install EPEL 
     yum : 
       name : epel-release
       update_cache : yes
       state : latest
     when : ansible_distribution == 'CentOS'
     tags : 
       - install-epel

   - name : Install nginx
     package : 
      name : nginx
      state : latest
     tags :
       - install-nginx

   - name : Install Patch
     yum : 
       name : patch
       update_cache : yes
       state : latest
     when : ansible_distribution == 'CentOS'   
     tags : 
       - patch-nginx

   - name : Patch nginx.conf to include sites-available, disable default server entry 
     patch : 
       src : files/nginx.conf.centos.patch
       dest : /etc/nginx/nginx.conf
     when : ansible_distribution == 'CentOS'   
     tags : 
       - patch-nginx

   - name : create /etc/nginx/sites-available directory if required 
     file : 
       path : /etc/nginx/sites-available
       state : directory
     tags :
       - patch-nginx

   - name : create /etc/nginx/sites-enabled directory if required 
     file : 
       path : /etc/nginx/sites-enabled
       state : directory
     tags :
       - patch-nginx

   - name : Copy default nginx configuration 
     copy : 
       src : files/nginx-default.conf
       dest : /etc/nginx/sites-available/default
     tags :
       - patch-nginx

   - name : Symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enabled/default 
     file : 
       src : /etc/nginx/sites-available/default
       dest : /etc/nginx/sites-enabled/default
       state : link
     tags :
       - patch-nginx
   
   - name : create nginx/html directory if required 
     file : 
       path : /usr/share/nginx/html
       state : directory
     tags :
       - patch-nginx

   - name : Template index.html.j2 to index.html on target 
     template : 
       src: templates/index.html.j2
       dest : /usr/share/nginx/html/index.html
       mode : 0644
     tags :
       - nginx-template

   - name : Restart nginx
     service :
       name : nginx
       state : restarted
     notify : Check Http Service
     tags : 
       - always

   - name : open Centos firewall for nginx
     firewalld :
       service : http
       permanent : true
       state : enabled
     when : ansible_distribution == 'CentOS'
     notify : Reload Firewall
     tags : 
       - nginx-open-firewall
...